<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" total="2" passed="1">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="7610" started-at="2016-05-18T08:42:39Z" finished-at="2016-05-18T08:42:47Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="7610" started-at="2016-05-18T08:42:39Z" finished-at="2016-05-18T08:42:47Z">
      <class name="QATools.QAMavenProject.LoginTestOnIndexPage">
        <test-method status="PASS" signature="beforeSuite()[pri:0, instance:QATools.QAMavenProject.LoginTestOnIndexPage@548a9f61]" name="beforeSuite" is-config="true" duration-ms="3017" started-at="2016-05-18T10:42:36Z" finished-at="2016-05-18T10:42:39Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeSuite -->
        <test-method status="PASS" signature="navigateToLogin()[pri:0, instance:QATools.QAMavenProject.LoginTestOnIndexPage@548a9f61]" name="navigateToLogin" is-config="true" duration-ms="2775" started-at="2016-05-18T10:42:39Z" finished-at="2016-05-18T10:42:42Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- navigateToLogin -->
        <test-method status="PASS" signature="testLoginWrongPasswd()[pri:1, instance:QATools.QAMavenProject.LoginTestOnIndexPage@548a9f61]" name="testLoginWrongPasswd" duration-ms="3164" started-at="2016-05-18T10:42:42Z" finished-at="2016-05-18T10:42:45Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testLoginWrongPasswd -->
        <test-method status="PASS" signature="navigateToLogin()[pri:0, instance:QATools.QAMavenProject.LoginTestOnIndexPage@548a9f61]" name="navigateToLogin" is-config="true" duration-ms="734" started-at="2016-05-18T10:42:45Z" finished-at="2016-05-18T10:42:46Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- navigateToLogin -->
        <test-method status="FAIL" signature="testLoginGoodPasswd()[pri:2, instance:QATools.QAMavenProject.LoginTestOnIndexPage@548a9f61]" name="testLoginGoodPasswd" duration-ms="927" started-at="2016-05-18T10:42:46Z" finished-at="2016-05-18T10:42:47Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:513)
	at org.testng.Assert.assertEqualsImpl(Assert.java:135)
	at org.testng.Assert.assertEquals(Assert.java:116)
	at org.testng.Assert.assertEquals(Assert.java:305)
	at org.testng.Assert.assertEquals(Assert.java:315)
	at QATools.QAMavenProject.LoginTestOnIndexPage.testLoginGoodPasswd(LoginTestOnIndexPage.java:44)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:643)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:820)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1128)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:126)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:137)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:58)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testLoginGoodPasswd -->
        <test-method status="PASS" signature="afterTest()[pri:0, instance:QATools.QAMavenProject.LoginTestOnIndexPage@548a9f61]" name="afterTest" is-config="true" duration-ms="345" started-at="2016-05-18T10:42:47Z" finished-at="2016-05-18T10:42:47Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterTest -->
      </class> <!-- QATools.QAMavenProject.LoginTestOnIndexPage -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
